repos:
  chaosMesh: 
   url: https://charts.chaos-mesh.org
   targetRevision: 2.8.2

  prometheus: 
    url: https://prometheus-community.github.io/helm-charts
    targetRevision: 82.18.0

  certManager:
    url: https://charts.jetstack.io
    targetRevision: v1.18.3
  
  config:
    url: https://github.com/jellebens/gitops.git
    targetRevision: HEAD
