clusterIssuer:
  enabled: true
  name: letsencrypt
  type: acme
  email: jellebens@outlook.com
  server: https://acme-v02.api.letsencrypt.org/directory
  privateKeySecretName: letsencrypt-account-key
  solver:
    ingressClassName: cilium
