clusterIssuer:
  enabled: true
  name: letsencrypt
  type: acme
  email: jellebens@outlook.com
  server: https://acme-v02.api.letsencrypt.org/directory
  privateKeySecretName: letsencrypt-account-key
  solver:
    ingressClassName: cilium

labCA:
  enabled: false
  selfSignedIssuerName: lab-selfsigned-root
  rootSecretName: lab-root-ca
  caIssuerName: lab-ca-issuer
  commonName: lab-root-ca
  duration: 87600h
  renewBefore: 720h
