clusterIssuer:
  enabled: true
  name: letsencrypt-prod
  email: jellebens@outlook.com
  server: https://acme-v02.api.letsencrypt.org/directory
  privateKeySecretName: letsencrypt-prod-account-key
  solver:
    ingressClassName: cilium
