apiVersion: v1
data:
  admin-password: Y2hhbmdlLW1lLW5vdw==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: observability:/Secret:observability/kube-prometheus-stack-grafana
  creationTimestamp: "2026-03-24T21:28:57Z"
  labels:
    app.kubernetes.io/component: admin-secret
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.3.3
    helm.sh/chart: grafana-11.1.8
  name: kube-prometheus-stack-grafana
  namespace: observability
  resourceVersion: "23249"
  uid: 41471f4f-21f3-4972-8f34-bb347a62ecba
type: Opaque
