apiVersion: v1
kind: Secret
metadata:
  name: config-repo
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-400"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: config-repo
  project: platform-services
  url: {{ .Values.repos.config.url | quote }}
  type: git