apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform-services
  sources:
    - repoURL: https://github.com/jellebens/gitops.git
      targetRevision: main
      path: platform/argocd-config
      helm:
        releaseName: argocd-config
        valueFiles:
          - $values/.config/shared/values.yaml
          - $values/.config/{{ .Values.environment | default "lab" }}/values.yaml
          - $values/.config/{{ .Values.environment | default "lab" }}/argocd.yaml
    - repoURL: https://github.com/jellebens/gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true