apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform-services
  sources:
    - repoURL: https://github.com/jellebens/gitops.git
      targetRevision: main
      path: platform/argocd-config
      helm:
        valueFiles:
          - $config/config/lab/argocd.yaml
    - repoURL: https://github.com/jellebens/gitops.git
      targetRevision: main
      ref: config
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true