apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform-services
  source:
    repoURL: https://github.com/jellebens/gitops.git
    targetRevision: main
    path: platform/argocd-config
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    createNamespace: true
    automated:
      prune: true
      selfHeal: true