{{- if .Values.secret.sealedSecret.encryptedData }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secret.name }}
  namespace: mqtt
spec:
  encryptedData:
    {{- range $k, $v := .Values.secret.sealedSecret.encryptedData }}
    {{- if $v }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
  template:
    metadata:
      name: {{ .Values.secret.name }}
      namespace: mqtt
    type: Opaque
{{- end }}
