apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: bootstrap
  source:
    repoURL: {{ .Values.applications.argocdIngress.repoURL }}
    targetRevision: {{ .Values.applications.argocdIngress.targetRevision }}
    path: {{ .Values.applications.argocdIngress.path }}
    directory:
      recurse: true
  destination:
    server: {{ .Values.global.clusterServer }}
    namespace: {{ .Values.global.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true