ipPools:
  - name: default
    disabled: false
    serviceSelector:
      matchLabels:
        lb-pool: default
    blocks:
      - start: 192.168.50.200
        stop: 192.168.50.240

  - name: infra
    disabled: false
    serviceSelector:
      matchLabels:
        lb-pool: infra
    blocks:
      - start: 192.168.50.160
        stop: 192.168.50.200

l2Policies:
  - name: default
    disabled: false
    nodeSelector: {}
    interfaces:
      - eth0
    loadBalancerIPs: true
    externalIPs: false