#!/usr/bin/env python3
"""Ceres Grafana dashboards — generated, never hand-edited (card #307).

    python3 generate.py            # (re)write the three JSON files next to this script
    python3 generate.py --check    # exit 1 when the files on disk differ from the generator

Three boards, one folder ("ceres", the sidecar picks the ConfigMap up — templates/dashboard.yaml):

  ceres-units   "Ceres — unit"        one unit at a time ($unit): status strip, water with the
                                      target band, mixing evidence, dosing, bottles, alerts, the
                                      learned row
  ceres-fleet   "Ceres — fleet"       every unit next to each other: Robigus alerts/advice,
                                      Carmenta's pool, Annona's registry
  ceres-ops     "Ceres — operations"  firmware desired vs running, OTA, config versions,
                                      service liveness, the archive's health

Sources (uids are provisioned in platform/observability-config):
  prometheus    ceres_* (Vertumnus), robigus_*, carmenta_*, ceres_annona_* — the live state
  influxdb      bucket `ceres` (Telegraf, landingzones/ceres/templates/telegraf-deployment.yaml):
                unit_tele{unit,zone,metric} unit_actuator{unit,actuator,metric}
                unit_meta{unit,metric[,actuator]} unit_docs{unit,doc} ceres_sys{metric[,service]}
  ceres-annona  PostgreSQL, read-only role `grafana` (views current_units, table unit_firmware)
"""

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
GENERATED = "Generated by landingzones/ceres/dashboards/generate.py (card #307) — edit the generator, not this file."

PROM = {"type": "prometheus", "uid": "prometheus"}
INFLUX = {"type": "influxdb", "uid": "influxdb"}
PG = {"type": "grafana-postgresql-datasource", "uid": "ceres-annona"}
MIXED = {"type": "datasource", "uid": "-- Mixed --"}

JAEGER = "http://jaeger.lab.local/search?service=ceres-vertumnus&lookback=6h"
INFLUX_UI = "http://influxdb.lab.local/orgs"
HIDE_PROM_LABELS = {"Time": True, "Value": True, "__name__": True, "instance": True, "job": True, "pod": True,
                    "namespace": True, "service": True, "container": True, "endpoint": True, "unit_type": True}


# ----------------------------------------------------------------------------- targets

PLAIN_SELECTOR = re.compile(r"[A-Za-z_:][A-Za-z0-9_:]*(\{(?:[^{}]|\$\{[^}]*\})*\})?")  # {unit="${unit}", …} nests a brace


def W(expr):
    """Fold the pod churn away: every rollout gives a gauge a new {pod, instance} series and a
    range query then returns one series per pod that lived in the window (found on the first
    render of the unit board — three ONLINEs in one stat)."""
    return f"max without (pod, instance) ({expr})"


def prom(expr, legend="", ref="A", instant=False, table=False):
    if not instant and PLAIN_SELECTOR.fullmatch(expr):
        expr = W(expr)
    t = {"datasource": PROM, "refId": ref, "expr": expr, "legendFormat": legend or "__auto",
         "range": not instant, "instant": instant, "editorMode": "code"}
    if table:
        t["format"] = "table"
    return t


def flux(query, ref="A"):
    return {"datasource": INFLUX, "refId": ref, "query": query}


def sql(raw, ref="A"):
    return {"datasource": PG, "refId": ref, "rawSql": raw, "format": "table", "rawQuery": True, "editorMode": "code"}


def tele(metric, zone, name, fn="mean", unit="${unit}", ref="A"):
    """One numeric telemetry series from the archive, windowed to the panel."""
    return flux(ref=ref, query=
        'from(bucket: "ceres") |> range(start: v.timeRangeStart, stop: v.timeRangeStop)'
        f' |> filter(fn: (r) => r._measurement == "unit_tele" and r.unit == "{unit}" and r.zone == "{zone}"'
        f' and r.metric == "{metric}" and r._field == "value")'
        f' |> aggregateWindow(every: v.windowPeriod, fn: {fn}, createEmpty: false)'
        f' |> keep(columns: ["_time", "_value"]) |> rename(columns: {{_value: "{name}"}})')


def meta_string(metric, name, actuator=None, unit="${unit}", start="v.timeRangeStart", stop="v.timeRangeStop", ref="A"):
    """A retained string (state/reason/status) from unit_meta as a time series of strings."""
    act = f' and r.actuator == "{actuator}"' if actuator else ""
    return flux(ref=ref, query=
        f'from(bucket: "ceres") |> range(start: {start}, stop: {stop})'
        f' |> filter(fn: (r) => r._measurement == "unit_meta" and r.unit == "{unit}" and r.metric == "{metric}"{act}'
        f' and r._field == "value") |> keep(columns: ["_time", "_value"]) |> rename(columns: {{_value: "{name}"}})')


# ----------------------------------------------------------------------------- panels

class Grid:
    """Places panels left to right, 24 columns wide, starting a new line when full."""

    def __init__(self, y=0):
        self.x, self.y, self.line_h = 0, y, 0

    def place(self, w, h):
        if self.x + w > 24:
            self.newline()
        pos = {"x": self.x, "y": self.y, "w": w, "h": h}
        self.x += w
        self.line_h = max(self.line_h, h)
        return pos

    def newline(self):
        if self.x:
            self.y += self.line_h
        self.x, self.line_h = 0, 0


_ids = iter(range(1, 10_000))


def _panel(kind, title, targets, pos, description="", datasource=None, unit=None, decimals=None,
           mappings=None, thresholds=None, overrides=None, options=None, transformations=None, extra=None):
    ds = datasource or (MIXED if len({json.dumps(t["datasource"], sort_keys=True) for t in targets}) > 1 else targets[0]["datasource"])
    defaults = {"color": {"mode": "thresholds" if thresholds else "palette-classic"}}
    if unit:
        defaults["unit"] = unit
    if decimals is not None:
        defaults["decimals"] = decimals
    if mappings:
        defaults["mappings"] = mappings
    if thresholds:
        defaults["thresholds"] = {"mode": "absolute", "steps": thresholds}
    p = {"id": next(_ids), "type": kind, "title": title, "description": (description + "\n\n" if description else "") + GENERATED,
         "datasource": ds, "gridPos": pos, "targets": targets,
         "fieldConfig": {"defaults": defaults, "overrides": overrides or []}, "options": options or {}}
    if transformations:
        p["transformations"] = transformations
    if extra:
        p.update(extra)
    return p


def instant_only(targets):
    """Single-value panels ask Prometheus for now, not for the range: no pod-churn duplicates."""
    for t in targets:
        if t["datasource"] is PROM:
            t["instant"], t["range"] = True, False
            if t["expr"].startswith("max without (pod, instance) ("):
                t["expr"] = t["expr"][len("max without (pod, instance) ("):-1]


def steps(*pairs):
    """thresholds: steps(("green", None), ("orange", 1), ("red", 3))"""
    return [{"color": c, "value": v} for c, v in pairs]


def value_map(**kv):
    """value_map(**{"1": ("ONLINE", "green"), "0": ("OFFLINE", "red")})"""
    return [{"type": "value", "options": {k: {"text": t, "color": c, "index": i} for i, (k, (t, c)) in enumerate(kv.items())}}]


def stat(title, targets, pos, description="", unit=None, decimals=None, mappings=None, thresholds=None,
         text_mode="value", color_mode="value", graph=False, no_value="—", reduce="lastNotNull"):
    opts = {"reduceOptions": {"calcs": [reduce], "fields": "", "values": False}, "orientation": "auto",
            "textMode": text_mode, "colorMode": color_mode, "graphMode": "area" if graph else "none",
            "justifyMode": "center", "wideLayout": True}
    instant_only(targets)
    p = _panel("stat", title, targets, pos, description, unit=unit, decimals=decimals, mappings=mappings,
               thresholds=thresholds or steps(("text", None)), options=opts)
    p["fieldConfig"]["defaults"]["noValue"] = no_value
    return p


def timeseries(title, targets, pos, description="", unit=None, decimals=None, overrides=None, min=None, max=None,
               fill=8, bars=False, stack=False, legend="bottom", thresholds_style=None, thresholds=None, mappings=None):
    custom = {"drawStyle": "bars" if bars else "line", "lineWidth": 1, "fillOpacity": fill, "gradientMode": "opacity",
              "showPoints": "never", "spanNulls": 3_600_000, "axisPlacement": "auto", "axisSoftMin": min}
    if stack:
        custom["stacking"] = {"mode": "normal", "group": "A"}
    if thresholds_style:
        custom["thresholdsStyle"] = {"mode": thresholds_style}
    p = _panel("timeseries", title, targets, pos, description, unit=unit, decimals=decimals, overrides=overrides,
               thresholds=thresholds, mappings=mappings,
               options={"legend": {"displayMode": "list", "placement": legend, "showLegend": True, "calcs": []},
                        "tooltip": {"mode": "multi", "sort": "none"}})
    p["fieldConfig"]["defaults"]["custom"] = custom
    if min is not None:
        p["fieldConfig"]["defaults"]["min"] = min
    if max is not None:
        p["fieldConfig"]["defaults"]["max"] = max
    return p


def state_timeline(title, targets, pos, description="", mappings=None, thresholds=None):
    p = _panel("state-timeline", title, targets, pos, description, mappings=mappings, thresholds=thresholds,
               options={"mergeValues": True, "showValue": "auto", "alignValue": "left", "rowHeight": 0.8,
                        "legend": {"displayMode": "list", "placement": "bottom", "showLegend": True},
                        "tooltip": {"mode": "single", "sort": "none"}})
    p["fieldConfig"]["defaults"]["custom"] = {"lineWidth": 0, "fillOpacity": 80}
    p["fieldConfig"]["defaults"]["color"] = {"mode": "thresholds"} if thresholds else {"mode": "palette-classic"}
    return p


def bargauge(title, targets, pos, description="", unit=None, min=0, max=100, thresholds=None, decimals=0):
    instant_only(targets)
    p = _panel("bargauge", title, targets, pos, description, unit=unit, decimals=decimals, thresholds=thresholds,
               options={"reduceOptions": {"calcs": ["lastNotNull"], "fields": "", "values": False},
                        "orientation": "horizontal", "displayMode": "gradient", "showUnfilled": True,
                        "valueMode": "color", "namePlacement": "left", "sizing": "auto"})
    p["fieldConfig"]["defaults"]["min"] = min
    p["fieldConfig"]["defaults"]["max"] = max
    return p


def table(title, targets, pos, description="", hide=None, rename=None, order=None, overrides=None, sort_by=None):
    tf = [{"id": "organize", "options": {"excludeByName": hide or {}, "renameByName": rename or {},
                                         "indexByName": {c: i for i, c in enumerate(order or [])}}}]
    if len(targets) > 1:
        tf.insert(0, {"id": "merge", "options": {}})
    opts = {"showHeader": True, "cellHeight": "sm", "footer": {"show": False}}
    if sort_by:
        opts["sortBy"] = [{"displayName": sort_by, "desc": False}]
    p = _panel("table", title, targets, pos, description, overrides=overrides, options=opts, transformations=tf)
    p["fieldConfig"]["defaults"]["custom"] = {"align": "auto", "cellOptions": {"type": "auto"}, "filterable": False}
    return p


def row(title, y, collapsed=False):
    return {"id": next(_ids), "type": "row", "title": title, "collapsed": collapsed,
            "gridPos": {"x": 0, "y": y, "w": 24, "h": 1}, "panels": []}


def override(name, **props):
    """override("pH low", color="red", dash=True, axis="right", hide_legend=True)"""
    out = []
    if "color" in props:
        out.append({"id": "color", "value": {"mode": "fixed", "fixedColor": props["color"]}})
    if props.get("dash"):
        out.append({"id": "custom.lineStyle", "value": {"fill": "dash", "dash": [10, 10]}})
    if "axis" in props:
        out.append({"id": "custom.axisPlacement", "value": props["axis"]})
    if "unit" in props:
        out.append({"id": "unit", "value": props["unit"]})
    if props.get("no_fill"):
        out.append({"id": "custom.fillOpacity", "value": 0})
    if props.get("stairs"):
        out.append({"id": "custom.lineInterpolation", "value": "stepAfter"})
    if "max" in props:
        out.append({"id": "max", "value": props["max"]})
    if "min" in props:
        out.append({"id": "min", "value": props["min"]})
    if "width" in props:
        out.append({"id": "custom.width", "value": props["width"]})
    if props.get("hide_legend"):
        out.append({"id": "custom.hideFrom", "value": {"legend": True, "tooltip": False, "viz": False}})
    matcher = {"id": "byRegexp", "options": name[1:]} if name.startswith("~") else {"id": "byName", "options": name}
    return {"matcher": matcher, "properties": out}


def dashboard(uid, title, panels, description, tags, variables=None, annotations=None, links=None, time_from="now-24h"):
    return {
        "uid": uid, "title": title, "description": description + "\n\n" + GENERATED, "tags": ["ceres", "hydroponics", *tags],
        "editable": True, "graphTooltip": 1, "timezone": "browser", "refresh": "1m", "schemaVersion": 39, "version": 1,
        "time": {"from": time_from, "to": "now"}, "timepicker": {}, "fiscalYearStartMonth": 0, "liveNow": False,
        "templating": {"list": variables or []},
        "annotations": {"list": [{"builtIn": 1, "datasource": {"type": "grafana", "uid": "-- Grafana --"}, "enable": True,
                                  "hide": True, "iconColor": "rgba(0, 211, 255, 1)", "name": "Annotations & Alerts",
                                  "type": "dashboard"}, *(annotations or [])]},
        "links": [{"title": "Ceres boards", "type": "dashboards", "tags": ["ceres"], "asDropdown": True, "includeVars": True,
                   "keepTime": True, "icon": "external link", "targetBlank": False, "tooltip": "", "url": ""},
                  *(links or [])],
        "panels": panels,
    }


def ext_link(title, url, tooltip=""):
    return {"title": title, "type": "link", "url": url, "tooltip": tooltip, "icon": "external link", "targetBlank": True,
            "asDropdown": False, "includeVars": False, "keepTime": False, "tags": []}


UNIT_VAR = {"type": "query", "name": "unit", "label": "Unit", "datasource": PROM, "refresh": 1, "sort": 1, "hide": 0,
            "multi": False, "includeAll": False, "definition": "label_values(ceres_unit_online, unit)",
            "query": {"query": "label_values(ceres_unit_online, unit)", "refId": "StandardVariableQuery"},
            "current": {"selected": False, "text": "pomona-0001", "value": "pomona-0001"}}

U = '{unit="${unit}"}'  # the unit selector for PromQL


def u(labels=""):
    return '{unit="${unit}"' + (", " + labels if labels else "") + "}"


L_PH, L_EC = u('metric="ph"'), u('metric="ec"')
L_PHD = u('reagent="ph_down"')
L_PH_LO, L_PH_HI = u('metric="ph", bound="low"'), u('metric="ph", bound="high"')
L_EC_LO, L_EC_HI = u('metric="ec_ms_cm", bound="low"'), u('metric="ec_ms_cm", bound="high"')


ONLINE = value_map(**{"1": ("ONLINE", "green"), "0": ("OFFLINE", "red")})
ROLE = value_map(**{"0": ("observe", "blue"), "1": ("advise", "purple"), "2": ("shadow", "orange"), "3": ("ACTIVE", "green")})
YES_NO = value_map(**{"1": ("yes", "orange"), "0": ("no", "green")})
UP_DOWN = value_map(**{"1": ("UP", "green"), "0": ("DOWN", "red")})
ONLINE_TXT = value_map(**{"online": ("ONLINE", "green"), "offline": ("OFFLINE", "red")})
ON_OFF = value_map(**{"on": ("on", "green"), "off": ("off", "dark-blue"), "1": ("on", "green"), "0": ("off", "dark-blue")})
OK_ALERT = value_map(**{"0": ("ok", "transparent"), "1": ("ALERT", "red")})


# ----------------------------------------------------------------------------- Ceres — unit

def unit_board():
    g = Grid()
    P = []

    # status strip — what the unit is right now
    P.append(stat("Node", [prom(f"ceres_unit_online{U}")], g.place(3, 4), "The node's retained LWT, as Vertumnus sees it.",
                  mappings=ONLINE, color_mode="background"))
    P.append(stat("Vertumnus role", [prom(f"ceres_unit_role{U}")], g.place(3, 4),
                  "Effective role: observe / advise / shadow / active (ADR-0010).", mappings=ROLE, color_mode="background"))
    P.append(stat("Firmware running", [prom(f"ceres_firmware_running{U} == 1", "{{version}}")], g.place(3, 4),
                  "The version the node reports (sys/meta).", text_mode="name", color_mode="none"))
    P.append(stat("Firmware desired", [prom(f"ceres_firmware_desired_match{U}")], g.place(3, 4),
                  "1 when the running version equals the one Annona wants (card #304); absent when no firmware is set.",
                  mappings=value_map(**{"1": ("MATCH", "green"), "0": ("UPDATE PENDING", "orange"), "-1": ("none set", "text")}),
                  color_mode="background", no_value="none set"))
    P.append(stat("Active alerts", [prom(f"count(robigus_alert_active{U} == 1) or vector(0)")], g.place(3, 4),
                  "Robigus's alert count for this unit.", thresholds=steps(("green", None), ("orange", 1), ("red", 3)),
                  color_mode="background"))
    P.append(stat("Advice", [prom(f"count(robigus_advice_active{U} == 1) or vector(0)")], g.place(3, 4),
                  "Robigus's standing advice for this unit.", thresholds=steps(("green", None), ("blue", 1)), color_mode="background"))
    P.append(stat("Mixing actuator", [prom(f"ceres_pump_power_watts{U}")], g.place(3, 4),
                  "Watts measured at the pump plug (Home Assistant → actuator/pump/power_w). The evidence a dose is mixing.",
                  unit="watt", decimals=1, thresholds=steps(("text", None), ("green", 1)), color_mode="value"))
    P.append(stat("Config version", [prom(f"ceres_config_version{U}")], g.place(3, 4),
                  "Version of the unit's config document Vertumnus runs on (Annona publishes it).", color_mode="none"))

    # second strip — the dosing state
    P.append(stat("pH now", [prom(f"ceres_reading{L_PH}")], g.place(3, 4), "Latest raw pH reading.",
                  decimals=2, color_mode="none"))
    P.append(stat("pH-Down last 24 h", [prom(f"ceres_budget_used_ml_24h{L_PHD}")], g.place(3, 4),
                  "Rolling 24 h of pH-Down delivered (the daily cap is 0 = off, owner's call 2026-09-13).", unit="mlitre",
                  decimals=1, color_mode="none"))
    P.append(stat("Last dose", [prom(f'max(ceres_last_dose_timestamp_seconds{U}) * 1000')], g.place(3, 4),
                  "When the last dose of any reagent was requested.", unit="dateTimeFromNow", color_mode="none"))
    P.append(stat("Dose pending", [prom(f"ceres_dose_response_pending{U}")], g.place(3, 4),
                  "1 while a dose waits for its mixed, fresh reading before Vertumnus judges the response (#303).",
                  mappings=YES_NO, color_mode="background"))
    P.append(stat("Lockout remaining", [prom(f"ceres_lockout_remaining_seconds{U}")], g.place(3, 4),
                  "Seconds until the next pH dose may be requested.", unit="s", decimals=0, color_mode="none"))
    P.append(stat("Planned pH dose", [prom(f"ceres_planned_ph_dose_ml{U}")], g.place(3, 4),
                  "The ml Vertumnus would dose now from the learned sensitivity (0 = nothing to do).", unit="mlitre",
                  decimals=1, color_mode="none"))
    P.append(stat("pH reading age", [prom(f"ceres_reading_age_seconds{L_PH}")], g.place(3, 4),
                  "Seconds since the last pH sample. Red when the node has gone quiet.", unit="s", decimals=0,
                  thresholds=steps(("green", None), ("orange", 120), ("red", 600)), color_mode="value"))
    P.append(stat("Stage", [prom(f"ceres_unit_stage{U} == 1", "{{stage}}"), prom(f"ceres_unit_reservoir_litres{U}", "reservoir L", "B")],
                  g.place(3, 4), "Growth stage (selects the target band) and the reservoir volume.", text_mode="value_and_name",
                  color_mode="none"))

    # water — with the target band from Vertumnus
    g.newline()
    P.append(timeseries("pH", [tele("ph", "water", "pH"),
                               prom(f"ceres_target{L_PH_LO}", "target low", "B"),
                               prom(f"ceres_target{L_PH_HI}", "target high", "C"),
                               prom(f"ceres_aim_ph{U}", "aim", "D")],
                        g.place(12, 9), "Archived pH (mean per window) with the stage's target band and the aim Vertumnus doses towards. Dose markers are annotations.",
                        decimals=2, fill=0, overrides=[override("target low", color="red", dash=True), override("target high", color="red", dash=True),
                                                       override("aim", color="green", dash=True), override("pH", color="blue")]))
    P.append(timeseries("EC (mS/cm)", [tele("ec_ms_cm", "water", "EC"),
                                       prom(f"ceres_target{L_EC_LO}", "target low", "B"),
                                       prom(f"ceres_target{L_EC_HI}", "target high", "C")],
                        g.place(12, 9), "Archived EC with the stage's target band.", decimals=2, fill=0,
                        overrides=[override("target low", color="red", dash=True), override("target high", color="red", dash=True),
                                   override("EC", color="yellow")]))
    P.append(timeseries("Temperatures", [tele("temp_c", "water", "water °C"), tele("temp_c", "air", "air °C", ref="B")],
                        g.place(8, 8), "Water and canopy air temperature.", unit="celsius", decimals=1, fill=0))
    P.append(timeseries("Canopy light", [tele("lux", "air", "lux"), prom(f"ceres_light_lit_hours_24h{U}", "lit h / 24 h", "B"),
                                         prom(f"ceres_light_required_hours{U}", "required h", "C")],
                        g.place(8, 8), "Lux at the canopy; the lit hours of the last 24 h against the profile's requirement on the right axis.",
                        decimals=0, fill=5, overrides=[override("lit h / 24 h", axis="right", unit="h", color="orange"),
                                                       override("required h", axis="right", unit="h", color="red", dash=True)]))
    P.append(timeseries("Air", [tele("humidity_pct", "air", "humidity %"), tele("pressure_hpa", "air", "pressure hPa", ref="B")],
                        g.place(8, 8), "Relative humidity and barometric pressure.", decimals=1, fill=0,
                        overrides=[override("pressure hPa", axis="right", unit="pressurehpa"), override("humidity %", unit="humidity")]))

    # mixing evidence and dosing
    g.newline()
    P.append(row("Mixing and dosing", g.y)); g.y += 1
    P.append(timeseries("Mixing evidence", [flux('from(bucket: "ceres") |> range(start: v.timeRangeStart, stop: v.timeRangeStop)'
                                                 ' |> filter(fn: (r) => r._measurement == "unit_actuator" and r.unit == "${unit}"'
                                                 ' and r.actuator == "pump" and r.metric == "power_w" and r._field == "value")'
                                                 ' |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)'
                                                 ' |> keep(columns: ["_time", "_value"]) |> rename(columns: {_value: "pump W"})'),
                                            prom(f"ceres_pump_running{U}", "pump requested", "B"),
                                            prom(f"ceres_pump_powered{U}", "pump powered", "C"),
                                            prom(f"ceres_mixing{U}", "mixing", "D")],
                        g.place(12, 8), "Measured watts (archive, max per window) against what Vertumnus believes: requested, powered, mixing (0/1, right axis). A request without watts is the #301 failure.",
                        unit="watt", decimals=1, fill=10,
                        overrides=[override("pump requested", axis="right", unit="none", max=1, stairs=True, no_fill=True, color="blue"),
                                   override("pump powered", axis="right", unit="none", max=1, stairs=True, no_fill=True, color="green"),
                                   override("mixing", axis="right", unit="none", max=1, stairs=True, no_fill=True, color="purple")]))
    P.append(state_timeline("Pump state and reason", [meta_string("state", "pump", actuator="pump"),
                                                       meta_string("reason", "reason", actuator="pump", ref="B"),
                                                       meta_string("state", "light", actuator="light", ref="C")],
                            g.place(12, 8), "Retained actuator state and the reason the node gives (schedule / override / …), plus the light.",
                            mappings=ON_OFF))
    P.append(timeseries("Delivered, rolling 24 h (ml)", [prom(f"ceres_budget_used_ml_24h{U}", "{{reagent}}")], g.place(8, 8),
                        "Rolling 24 h ml per reagent as the ledger counts it.", unit="mlitre", decimals=1, fill=15))
    P.append(timeseries("Decisions per hour", [prom(f"sum by (action) (increase(ceres_decisions_total{U}[1h]))", "{{action}}")],
                        g.place(8, 8), "What Vertumnus decided, per hour: doses, blocked doses, alerts.", decimals=0, bars=True, stack=True, fill=70))
    P.append(timeseries("Pending dose: mixed and powered time", [prom(f"ceres_pending_dose_mixed_seconds{U}", "mixed s"),
                                                                 prom(f"ceres_pending_dose_powered_seconds{U}", "powered s", "B")],
                        g.place(8, 8), "Since the pending dose: seconds the pump was on (requested) and seconds it drew power. The verdict needs the mixing time (#303).",
                        unit="s", decimals=0, fill=0))

    # bottles
    g.newline()
    P.append(row("Bottles", g.y)); g.y += 1
    P.append(bargauge("Reagent remaining", [prom(f"ceres_reagent_remaining_ml{U} / ceres_reagent_container_ml{U} * 100", "{{reagent}}")],
                      g.place(8, 6), "Remaining as a share of the container, from the fill Annona knows and the ml pumped since.",
                      unit="percent", thresholds=steps(("red", None), ("orange", 15), ("green", 35))))
    P.append(stat("Remaining (ml)", [prom(f"ceres_reagent_remaining_ml{U}", "{{reagent}}")], g.place(8, 6),
                  "Millilitres left per bottle.", unit="mlitre", decimals=0, text_mode="value_and_name", color_mode="none"))
    P.append(stat("Days left at the current rate", [prom(f"(ceres_reagent_remaining_ml{U} * on(unit) group_left() ceres_dosing_window_hours{U}) / 24 / ceres_dosing_rate_mean_ml{U}", "{{reagent}}")],
                  g.place(8, 6), "Remaining ml over the learned dosing rate (Model C mean per window, scaled to a day). ∞ while a reagent is not being dosed.",
                  unit="d", decimals=0, text_mode="value_and_name", thresholds=steps(("red", None), ("orange", 3), ("green", 7)), color_mode="value"))
    P.append(timeseries("Reagent level (ml)", [prom(f"ceres_reagent_remaining_ml{U}", "{{reagent}}")], g.place(12, 8),
                        "Bottle levels over time; a step up is a refill registered in Annona.", unit="mlitre", decimals=0, fill=10))
    P.append(state_timeline("Alerts", [prom(f"ceres_alert_active{U}", "{{condition}}")], g.place(12, 8),
                            "Vertumnus's alert conditions over time (1 = active).", mappings=OK_ALERT,
                            thresholds=steps(("transparent", None), ("red", 1))))

    # learned
    g.newline()
    P.append(row("What Vertumnus learned", g.y)); g.y += 1
    P.append(stat("pH-Down sensitivity k (pH/ml)", [prom(f"ceres_ph_sensitivity_ph_per_ml{U}", "k"), prom(f"ceres_ph_sensitivity_sd{U}", "sd", "B")],
                  g.place(5, 4), "Model A: pH drop per ml, with its standard deviation. Starts from the profile prior (or Carmenta's pool) and tightens with each verified dose.",
                  decimals=3, text_mode="value_and_name", color_mode="none"))
    P.append(stat("Learned from n doses", [prom(f"ceres_ph_sensitivity_observations{U}")], g.place(3, 4), "Verified dose responses folded into k.", decimals=0, color_mode="none"))
    P.append(stat("Buffer knee b (pH)", [prom(f"ceres_ph_buffer_knee_ph{U}")], g.place(3, 4), "Where the tank's buffering bends the response.", decimals=2, color_mode="none"))
    P.append(stat("Settle time", [prom(f"ceres_learned_settle_seconds{U}")], g.place(3, 4), "How long after a dose the reading is trusted.", unit="s", decimals=0, color_mode="none"))
    P.append(stat("Probe noise sd (pH)", [prom(f"ceres_learned_noise_ph{U}")], g.place(3, 4), "Model B's measurement noise.", decimals=3, color_mode="none"))
    P.append(stat("Rebound (pH/h)", [prom(f"ceres_learned_rebound_ph_per_hour{U}")], g.place(3, 4), "How fast pH drifts back up between doses.", decimals=3, color_mode="none"))
    P.append(stat("No-response streak", [prom(f"ceres_no_response_streak{U}")], g.place(4, 4), "Consecutive doses without a measurable drop. Three in a row is an alert.",
                  decimals=0, thresholds=steps(("green", None), ("orange", 1), ("red", 3)), color_mode="value"))
    K, SD = W(f"ceres_ph_sensitivity_ph_per_ml{U}"), W(f"ceres_ph_sensitivity_sd{U}")
    P.append(timeseries("Sensitivity k over time (learning curve)", [prom(f"ceres_ph_sensitivity_ph_per_ml{U}", "k"),
                                                                     prom(f"{K} + {SD}", "k + sd", "B"),
                                                                     prom(f"{K} - {SD}", "k − sd", "C")],
                        g.place(12, 8), "k with its ±1 sd band.", decimals=3, fill=0,
                        overrides=[override("k + sd", color="gray", dash=True), override("k − sd", color="gray", dash=True)]))
    P.append(timeseries("Dose responses (pH drop) and the streak", [prom(f"ceres_last_dose_response_ph_drop{U}", "last drop (pH)"),
                                                                    prom(f"ceres_no_response_streak{U}", "streak", "B")],
                        g.place(12, 8), "Verified pH drop of the last dose and the no-response streak (right axis).", decimals=2, fill=0,
                        overrides=[override("streak", axis="right", stairs=True, color="orange")]))
    P.append(timeseries("Dosing-rate baseline (Model C, ml per window)", [prom(f"ceres_dosing_rate_mean_ml{U}", "usual {{reagent}}"),
                                                                          prom(f"ceres_dosing_window_ml{U}", "this window {{reagent}}", "B")],
                        g.place(12, 8), "The usual ml per window against the current window — the dosing_unusual alerts compare these.", unit="mlitre", decimals=1, fill=0))
    P.append(timeseries("Filtered pH and its drift (Model B)", [prom(f"ceres_ph_filtered{U}", "filtered pH"),
                                                                prom(f"ceres_ph_slope_per_hour{U}", "slope pH/h", "B")],
                        g.place(12, 8), "Kalman-filtered pH and its slope (right axis).", decimals=3, fill=0,
                        overrides=[override("slope pH/h", axis="right", color="purple")]))

    annotations = [{"datasource": PROM, "enable": True, "hide": False, "iconColor": "blue", "name": "Doses",
                    "expr": 'increase(ceres_doses_total{unit="${unit}"}[2m]) > 0', "step": "1m", "titleFormat": "dose {{reagent}}",
                    "textFormat": "", "useValueForTime": False},
                   {"datasource": PROM, "enable": True, "hide": False, "iconColor": "red", "name": "Blocked doses",
                    "expr": 'increase(ceres_decisions_total{unit="${unit}", action="blocked"}[2m]) > 0', "step": "1m",
                    "titleFormat": "blocked: {{condition}}", "textFormat": "", "useValueForTime": False}]
    return dashboard("ceres-units", "Ceres — unit", P,
                     "One unit at a time: what the node reports, what Vertumnus believes and decides, what it has learned. Sources: Prometheus (live state), the ceres Influx archive (history).",
                     ["unit", "vertumnus"], variables=[UNIT_VAR], annotations=annotations,
                     links=[ext_link("Traces (Jaeger)", JAEGER, "ceres-vertumnus spans: one trace per dose (card #302)")])


# ----------------------------------------------------------------------------- Ceres — fleet

def fleet_board():
    g = Grid()
    P = []
    P.append(stat("Units registered", [prom("ceres_annona_units")], g.place(3, 4), "Units in Annona's registry (not retired).", decimals=0, color_mode="none"))
    P.append(stat("Units online", [prom("sum(ceres_unit_online) or vector(0)")], g.place(3, 4), "Nodes whose LWT says online.", decimals=0,
                  thresholds=steps(("red", None), ("green", 1)), color_mode="value"))
    P.append(stat("Fleet mode", [prom("ceres_annona_info", "{{fleet_mode}}")], g.place(3, 4), "Annona's fleet mode (ceres/sys/mode).", text_mode="name", color_mode="none"))
    P.append(stat("Critical alerts", [prom('count(robigus_alert_active{severity="critical"} == 1) or vector(0)')], g.place(3, 4), "Across all units.",
                  decimals=0, thresholds=steps(("green", None), ("red", 1)), color_mode="background"))
    P.append(stat("Warnings", [prom('count(robigus_alert_active{severity="warning"} == 1) or vector(0)')], g.place(3, 4), "Across all units.",
                  decimals=0, thresholds=steps(("green", None), ("orange", 1)), color_mode="background"))
    P.append(stat("Advice", [prom("(count(robigus_advice_active == 1) or vector(0)) + (count(carmenta_advice_active == 1) or vector(0))")], g.place(3, 4),
                  "Standing advice: Robigus (per unit) plus Carmenta (fleet: shopping, placement).", decimals=0, thresholds=steps(("green", None), ("blue", 1)), color_mode="background"))
    P.append(stat("Pool contributors", [prom("carmenta_pool_contributors")], g.place(3, 4), "Units whose learned k feeds Carmenta's pooled prior.", decimals=0, color_mode="none"))
    P.append(stat("Priors published", [prom("carmenta_priors_published")], g.place(3, 4), "Pooled priors Carmenta has handed to units that learned nothing yet.", decimals=0, color_mode="none"))

    g.newline()
    P.append(table("Active alerts", [prom("robigus_alert_active == 1", instant=True, table=True)], g.place(12, 8),
                   "Robigus's alerts right now, every unit.", hide=HIDE_PROM_LABELS, order=["unit", "severity", "condition"],
                   overrides=[override("severity", width=110), override("unit", width=140)], sort_by="severity"))
    P.append(table("Advice", [prom("robigus_advice_active == 1", instant=True, table=True, ref="A"),
                              prom("carmenta_advice_active == 1", instant=True, table=True, ref="B")], g.place(12, 8),
                   "Robigus's per-unit advice and Carmenta's fleet advice (no unit).", hide=HIDE_PROM_LABELS, order=["unit", "severity", "kind"],
                   overrides=[override("severity", width=110), override("unit", width=140)]))
    P.append(table("Registry (Annona)", [sql("select unit_id as unit, type, node, stage, reservoir_l as \"reservoir L\", established_from as \"established from\", version as \"config version\" from current_units order by unit_id")],
                   g.place(24, 6), "Annona's current units and their facts (view current_units)."))

    g.newline()
    P.append(timeseries("pH, every unit", [prom('ceres_reading{metric="ph"}', "{{unit}}")], g.place(12, 8), "Raw pH per unit.", decimals=2, fill=0))
    P.append(timeseries("EC, every unit", [prom('ceres_reading{metric="ec"}', "{{unit}}")], g.place(12, 8), "Raw EC per unit (mS/cm).", decimals=2, fill=0))
    P.append(timeseries("Sensitivity k: units against Carmenta's pool", [prom("ceres_ph_sensitivity_ph_per_ml", "{{unit}}"),
                                                                          prom("carmenta_pool_kv_mean", "pool mean", "B"),
                                                                          prom(f"{W('carmenta_pool_kv_mean')} + {W('carmenta_pool_kv_sd')}", "pool + sd", "C"),
                                                                          prom(f"{W('carmenta_pool_kv_mean')} - {W('carmenta_pool_kv_sd')}", "pool − sd", "D")],
                        g.place(12, 8), "Each unit's learned pH-Down sensitivity next to the pooled prior (ADR-0012).", decimals=3, fill=0,
                        overrides=[override("pool mean", color="gray", dash=True), override("pool + sd", color="gray", dash=True, hide_legend=True),
                                   override("pool − sd", color="gray", dash=True, hide_legend=True)]))
    P.append(timeseries("Alerts per unit", [prom("robigus_alerts", "{{unit}}")], g.place(12, 8), "Robigus's alert count per unit over time.",
                        decimals=0, fill=10, overrides=[override("~.*", stairs=True)]))
    return dashboard("ceres-fleet", "Ceres — fleet", P,
                     "Every unit next to each other: Robigus's alerts and advice, Carmenta's pooled learning, Annona's registry.",
                     ["fleet", "robigus", "carmenta", "annona"])


# ----------------------------------------------------------------------------- Ceres — operations

def ops_board():
    g = Grid()
    P = []
    P.append(stat("Annona database", [prom("ceres_annona_db_up")], g.place(3, 4), "PostgreSQL (CNPG ceres-pg) reachable from Annona.", mappings=UP_DOWN, color_mode="background"))
    P.append(stat("Annona requests / min", [prom("sum(rate(ceres_annona_requests_total[5m])) * 60 or vector(0)")], g.place(3, 4),
                  "HTTP requests to Annona's API.", decimals=1, color_mode="none"))
    P.append(stat("OTA requests", [prom("sum(increase(ceres_ota_requests_total[$__range])) or vector(0)")], g.place(3, 4),
                  "OTA URLs published to nodes in the dashboard's time range (card #304).", decimals=0, color_mode="none"))
    P.append(stat("Firmware mismatches", [prom("count(ceres_firmware_desired_match == 0) or vector(0)")], g.place(3, 4),
                  "Units whose running firmware differs from Annona's desired version.", decimals=0,
                  thresholds=steps(("green", None), ("orange", 1)), color_mode="background"))
    P.append(stat("Archive: last telemetry", [flux('from(bucket: "ceres") |> range(start: -30d) |> filter(fn: (r) => r._measurement == "unit_tele" and r._field == "value")'
                                                    ' |> group() |> last() |> map(fn: (r) => ({_value: float(v: uint(v: r._time)) / 1000000.0})) |> keep(columns: ["_value"])')],
                  g.place(3, 4), "Newest point in the ceres bucket's unit_tele. Should be seconds old.", unit="dateTimeFromNow", color_mode="none"))
    P.append(stat("Archive: points / h", [flux('from(bucket: "ceres") |> range(start: -1h) |> filter(fn: (r) => r._field == "value") |> group() |> count() |> keep(columns: ["_value"])')],
                  g.place(3, 4), "Points written to the ceres bucket in the last hour (all measurements).", decimals=0, color_mode="none"))
    P.append(stat("Vertumnus instances", [prom("count(ceres_info) or vector(0)")], g.place(3, 4), "Running Vertumnus controllers.", decimals=0, color_mode="none"))
    P.append(stat("Robigus / Carmenta", [prom("count(ceres_robigus_info) or vector(0)", "Robigus"), prom("count(ceres_carmenta_info) or vector(0)", "Carmenta", "B")],
                  g.place(3, 4), "Running instances.", decimals=0, text_mode="value_and_name", color_mode="none"))

    g.newline()
    P.append(row("Firmware and configuration", g.y)); g.y += 1
    P.append(table("Firmware: desired (Annona)", [sql("select distinct on (unit_id) unit_id as unit, version as desired, url, valid_from as since from unit_firmware order by unit_id, valid_from desc, id desc")],
                   g.place(12, 7), "What each unit should run — PUT /units/<id>/firmware (card #304). Empty until a version is set.",
                   overrides=[override("since", unit="dateTimeAsIso")]))
    P.append(table("Firmware: running (nodes)", [prom("ceres_firmware_running == 1", instant=True, table=True, ref="A"),
                                                  prom("ceres_firmware_desired_match", instant=True, table=True, ref="B")], g.place(12, 7),
                   "The version each node reports and whether it matches the desired one (1 = match, 0 = pending, empty = none desired).",
                   hide={**HIDE_PROM_LABELS, "Value #A": True}, rename={"Value #B": "matches desired"}, order=["unit", "version", "matches desired"]))
    P.append(table("Config versions (Annona)", [sql("select unit_id as unit, version, published_at as published from config_versions where (unit_id, version) in (select unit_id, max(version) from config_versions group by unit_id) order by unit_id")],
                   g.place(12, 7), "Newest published config document per unit.", overrides=[override("published", unit="dateTimeAsIso")]))
    P.append(timeseries("Config version running on the unit", [prom("ceres_config_version", "{{unit}}")], g.place(12, 7),
                        "The version each Vertumnus runs on; a step is a config publish taking effect.", decimals=0, fill=0,
                        overrides=[override("~.*", stairs=True)]))

    g.newline()
    P.append(row("Services and the archive", g.y)); g.y += 1
    P.append(state_timeline("Service liveness (ceres/sys/status/*)", [flux('from(bucket: "ceres") |> range(start: v.timeRangeStart, stop: v.timeRangeStop)'
                                                                           ' |> filter(fn: (r) => r._measurement == "ceres_sys" and r.metric == "status" and r._field == "value")'
                                                                           ' |> keep(columns: ["_time", "_value", "service"]) |> group(columns: ["service"])')],
                            g.place(12, 7), "Retained LWTs of the services as archived. A retained value only changes on connect/disconnect, so a quiet row is a healthy one.",
                            mappings=ONLINE_TXT))
    P.append(timeseries("Annona requests by status", [prom("sum by (status) (rate(ceres_annona_requests_total[5m])) * 60", "{{status}}")], g.place(12, 7),
                        "Requests per minute to Annona's API by HTTP status.", decimals=1, bars=False, fill=20, stack=True))
    P.append(table("Archive: newest point per measurement", [flux('from(bucket: "ceres") |> range(start: -30d) |> filter(fn: (r) => r._field == "value")'
                                                                  ' |> group(columns: ["_measurement"]) |> last() |> keep(columns: ["_measurement", "_time"]) |> group()'
                                                                  ' |> rename(columns: {_measurement: "measurement", _time: "newest point"})')],
                   g.place(12, 7), "Per measurement in the ceres bucket: when the last point landed. Telegraf's own stats are not written here (Prometheus only).",
                   overrides=[override("newest point", unit="dateTimeFromNow")]))
    P.append(timeseries("Archive: points per hour by measurement", [flux('from(bucket: "ceres") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._field == "value")'
                                                                         ' |> group(columns: ["_measurement"]) |> aggregateWindow(every: 1h, fn: count, createEmpty: false)'
                                                                         ' |> keep(columns: ["_time", "_value", "_measurement"])')],
                        g.place(12, 7), "Write volume into the forever bucket, per measurement.", decimals=0, bars=True, stack=True, fill=70))
    return dashboard("ceres-ops", "Ceres — operations", P,
                     "Running the fleet: firmware desired vs running, OTA, configuration versions, service liveness, the archive's health.",
                     ["operations", "annona", "firmware", "telegraf"],
                     links=[ext_link("Traces (Jaeger)", JAEGER), ext_link("InfluxDB", INFLUX_UI), ext_link("Firmware server", "http://firmware.lab.local/")],
                     time_from="now-7d")


# ----------------------------------------------------------------------------- main

BOARDS = {"ceres-unit.json": unit_board, "ceres-fleet.json": fleet_board, "ceres-operations.json": ops_board}


def render(build):
    return json.dumps(build(), indent=1, ensure_ascii=False) + "\n"


def main(argv):
    check = "--check" in argv
    stale = []
    for name, build in BOARDS.items():
        path = HERE / name
        text = render(build)
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(name)
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(HERE.parent.parent.parent)}")
    if stale:
        print("stale (run generate.py):", ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
