{{- range .Values.extraSecrets }}
{{- if .sealedSecret.encryptedData }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  encryptedData:
    {{- range $k, $v := .sealedSecret.encryptedData }}
    {{- if $v }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
  template:
    metadata:
      name: {{ .name }}
      namespace: {{ .namespace }}
    type: Opaque
{{- end }}
{{- end }}
