{{- range .Values.extraStorageClasses }}
{{- $secName := .secretName | default $.Values.secret.name }}
{{- $secNs := .secretNamespace | default $.Values.secret.namespace }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
provisioner: smb.csi.k8s.io
parameters:
  source: {{ .source | quote }}
  csi.storage.k8s.io/provisioner-secret-name: {{ $secName }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ $secNs }}
  csi.storage.k8s.io/node-stage-secret-name: {{ $secName }}
  csi.storage.k8s.io/node-stage-secret-namespace: {{ $secNs }}
reclaimPolicy: {{ .reclaimPolicy | default "Retain" }}
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid={{ .uid }}
  - gid={{ .gid }}
  - noperm
  - mfsymlinks
  - cache=strict
{{- end }}
