apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-lab
  namespace: kube-system
  labels:
    app.kubernetes.io/name: coredns-lab
    app.kubernetes.io/part-of: platform
data:
  Corefile: |
    {{ .Values.corednsLab.zone }}:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        file /etc/coredns-zones/db.{{ .Values.corednsLab.zone }}
        {{- if .Values.corednsLab.transferTo }}
        transfer {
            to {{ join " " .Values.corednsLab.transferTo }}
        }
        {{- end }}
        prometheus :9153
        cache 30
        loadbalance
        log
    }
    .:53 {
        errors
        cache 30
        forward . {{ join " " (required "corednsLab.upstreams is required" .Values.corednsLab.upstreams) }} {
            policy sequential
        }
        loadbalance
        log
    }
