---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ceres-pg-grafana
  namespace: ceres
spec:
  encryptedData:
    password: AgBKiwSVVEywlLErnqpTE+kpxSVm34KmyQLJQOH6VR98hxrzBbkRYcI8+fz1RbK8fNIf8priLwuQoK5hYfxa+Bsd9kGQ5yClpEwYpe6LpLYvg+rx6g8hdPNwh18tLYikL/FUzMRhT7G41SQ5qkCBippDKVKJ9aDD1pbLt8A/0bP5brTlaxmgMXxQSJLknps4NOHYPCb+te5ARBugXB6WM1XvJl96EkuSXd6F289VBXDLmm9fy6OlBMlDNAnnLvIz3vRaKVF47KBrGK54WSCgfhwlAEYAhJkxSrwFtMbCZgxynek2IBnGAStJFfCkQfG+vhGwUcyfpTSMIXkDlQAj40xiMvkR9mEM74WJt1746PWeThbykvW5CB7cs6+DCeikhzArykTYJjMqsdMFXJ7Xh+DZmfwC3qE8zfkF/fG6LU9M5l7svJVBkU+cUVAZ8/bE73bFZkuUtU0jSs2189YU/XBZ0TftH0BW282NOLWdN/wafnlLlcNIb7hOf4TKMM03oEK6/67WyqchUOLxFZd9xJhJccUbIu4OGQigC+gxPxXtVQSRSimlwg0daz7eBXASWmq4qk9jrTISZ1UVEJJVxyje5G2yjg2AqqCG5yYAfDUpdvtjy6MDjV2nY4bQAIDSFl7x6KKUTt3qNz6ouM0VmMki/pokSbG72TX7qPy8NAiheu+VL2gO2k/2lqcGJpeLLXPRViYEEDmOh2h3wbL0FfBv9jaTo0leUKsmL8VknU9PIA==
    username: AgDh2dbXHQW2wy6nvEItxJJXB4g9yO06bvK+yHXnclctw5Nbi5E8Of6MUnfWwpfWZUUfXtf/dv85yVr3mnpzoiFk7YlHf0bJGptwMRbcuo+NMtCaIBzzvv+v8/DlfEUHw1dVVE2UoJSFeFSQKXa3LUKnY12RP2WwLduQbQ4/2jShx1gBngEq7QXW0ET1NhJTGYQq1zIldUs8qaqja7xO83MEZNK3Vj0rdeKxNRsNxu81OHRSMa1F54ZGXcPjIZ9lIoHMOM9bGjaogRlIoDejCYIk4YEX412u5pjxivmiw7NwjNdgW8q/iNgHBS+oUihfrHHHPUgIXoZ2rNlAA8hLQxiWOOdpOJ85CioN5U2/ItQ1GzYkOqqexXpzKp4gt53DMvN8rV0tRMaZhWBJxuIQkjQHOMpwteamGDTvjn1F3bIc+IPKCsYpNqsu8eKxu/h3ZKUPTfaZT6rcHz7yIoE+l+oCB2kOIIcdBt0EhVaMWLP0lqHSTXLJ/ZjQPzYRuFm3v87J9L5fJHJno4pl457DVT3ZVkNvg5L6jMUY0wJUtQERBWXrbtAXJMrcvwnYY8PzqrJ60wjU5l5ccnR1zTnDUlDD1YUQ2uzltr2exQSM7i/MLbefsRcsCUfSba3YxG322N+zZhGCr0xDjLyL1KoU8/aFklUZztkd55BiZHtzCh8C/pXQG/Haw2GjvitbmWiWTpl0cqoOieHe
  template:
    metadata:
      name: ceres-pg-grafana
      namespace: ceres
