{{- if .Values.metrics.enabled }}
{{- range $id, $u := .Values.units }}
{{- if $u.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: ceres-vertumnus-{{ $id }}-metrics
  namespace: ceres
  labels:
    app.kubernetes.io/name: ceres-vertumnus
    app.kubernetes.io/instance: ceres-vertumnus-{{ $id }}
    app.kubernetes.io/part-of: ceres
    ceres.jellebens.dev/unit: {{ $id | quote }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: ceres-vertumnus-{{ $id }}
  ports:
    - name: metrics
      port: {{ $.Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- if $.Values.vertumnus.apiPort }}
    - name: api
      port: {{ $.Values.vertumnus.apiPort }}
      targetPort: api
      protocol: TCP
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
