apiVersion: v1
kind: ConfigMap
metadata:
  name: cortana-config
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    app.kubernetes.io/name: cortana
    app.kubernetes.io/part-of: cortana
data:
  config.yaml: |-
    {{- toYaml .Values.config | nindent 4 }}
