{{- if and .Values.dashboard.enabled .Values.gateway.httpToHttpsRedirect.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cortana-http-to-https
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    app.kubernetes.io/name: cortana
    app.kubernetes.io/part-of: cortana
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.parentRef.name }}
      {{- with .Values.gateway.parentRef.namespace }}
      namespace: {{ . }}
      {{- end }}
      sectionName: {{ .Values.gateway.httpToHttpsRedirect.sectionName }}
  hostnames:
    {{- toYaml .Values.gateway.hostnames | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 302
{{- end }}
