{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | quote }}
  labels:
    app.kubernetes.io/name: cortana
    app.kubernetes.io/part-of: cortana
{{- end }}
