{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cortana-state
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    app.kubernetes.io/name: cortana
    app.kubernetes.io/part-of: cortana
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
