{{- if and .Values.openai.enabled .Values.openai.sealedSecret.encryptedApiKey }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.openai.secretName | quote }}
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    app.kubernetes.io/name: cortana
    app.kubernetes.io/part-of: cortana
spec:
  encryptedData:
    {{ .Values.openai.secretKey }}: {{ .Values.openai.sealedSecret.encryptedApiKey }}
  template:
    metadata:
      name: {{ .Values.openai.secretName | quote }}
      namespace: {{ .Values.namespace.name | quote }}
    type: Opaque
{{- end }}
{{- if and .Values.discord.enabled .Values.discord.sealedSecret.encryptedToken }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.discord.secretName | quote }}
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    app.kubernetes.io/name: cortana
    app.kubernetes.io/part-of: cortana
spec:
  encryptedData:
    {{ .Values.discord.secretKey }}: {{ .Values.discord.sealedSecret.encryptedToken }}
  template:
    metadata:
      name: {{ .Values.discord.secretName | quote }}
      namespace: {{ .Values.namespace.name | quote }}
    type: Opaque
{{- end }}
{{- if and .Values.todoist.enabled .Values.todoist.sealedSecret.encryptedToken }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.todoist.secretName | quote }}
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    app.kubernetes.io/name: cortana
    app.kubernetes.io/part-of: cortana
spec:
  encryptedData:
    {{ .Values.todoist.secretKey }}: {{ .Values.todoist.sealedSecret.encryptedToken }}
  template:
    metadata:
      name: {{ .Values.todoist.secretName | quote }}
      namespace: {{ .Values.namespace.name | quote }}
    type: Opaque
{{- end }}
