{{- if .Values.dashboard.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cortana
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    app.kubernetes.io/name: cortana
    app.kubernetes.io/part-of: cortana
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: cortana
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
{{- end }}
