apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zeus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: landing-zones
  destination:
    server: https://kubernetes.default.svc
    namespace: zeus
  sources:
    - repoURL: {{ .Values.repos.config.url | quote }}
      targetRevision: {{ .Values.repos.config.targetRevision | default "HEAD" }}
      path: landingzones/zeus
      helm:
        releaseName: zeus
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/.config/shared/values.yaml
          - $values/.config/{{ .Values.environment | default "lab" }}/values.yaml
          - $values/.config/{{ .Values.environment | default "lab" }}/zeus.yaml
    - repoURL: {{ .Values.repos.config.url | quote }}
      targetRevision: {{ .Values.repos.config.targetRevision | default "HEAD" }}
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
