apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-config
  namespace: argocd
  annotations:
    cilium.argoproj.io/sync-wave: "5"
spec:
  project: platform-services
  source:
    repoURL: https://github.com/jellebens/gitops.git
    targetRevision: main
    path: platform/cilium-config
    helm:
      valueFiles:
        - ../config/lab/cilium.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cilium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true