apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-config
  namespace: argocd
  annotations:
    cilium.argoproj.io/sync-wave: "5"
spec:
  project: platform-services
  sources:  
    - repoURL: https://github.com/jellebens/gitops.git
      type: git
      targetRevision: main
      path: platform/cilium-config
      helm:
        valueFiles:
          - $config/lab/cilium.yaml  
    - repoURL: https://github.com/jellebens/gitops.git
      targetRevision: main
      path: config
      ref: config
  destination:
    server: https://kubernetes.default.svc
    namespace: cilium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true