---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-ceres-postgres
  namespace: observability
spec:
  encryptedData:
    CERES_PG_PASSWORD: AgAGvPyqovclE9VKtFwoybaslDcme3B2q581u/RHZORNJl+ONuZgSRyEBTVTQKCuhVKXtVlYk+D22z1KwjnuOn8GfqENY0KCTl/7bsM14t66VLTYJfjrTw+WuLV+i8LO/mK28LxTFgWSs0r6WvypEeR7KwnanKbxTOUCcSJ/WrBjm48X6KRE/ndzbJ/zQWmHUo64jG7jAzJ/bhe0QFFYwI2iGz7O1yPa7ZCG0Bxybj38h48GrJJWmX08vDu8a/F8Z8yAn7kFWHcecv0cpF2at+t3g/ajEFTQzPATKw7ad/yWSp0iiUmn4BuGuokY3IBnlo63Zf6jLjUKr621pynWvkvPfQJcNhma4l/GYe0PbVJMPeQVvP1ZKQVzD2TY1yZRFYa6zTNKd+ZUuNEOSjScLQybQvyfDmDshVFphXJpqe3dFAIR5MD+EmxptbAvwUNxGobHdBfhCRcFQWciLhBFtdj3PJZ0KEX2Ujnx5I6Fx+nvdKjc8IOQ1p59ZyQvs3IKA8tSVT6tOUqSAMn4gQdf9DuV99eD5KK4UkbV20proEnizn6VsoD7HI21Wes8KXVa/7BUPfHGMUQMlP9ugk9jkTldMxq/+bWJC+3Y1CU0agIc9YoefO88eqrYzic9u/3iHlfxS+Y4DjGztDQUzpsp2l7xi0GXk5PxUsEoHOZwIrPaV7r/gxT40QJeHC3rsC0FEPGielxzH8TX/J/8j/t+BNPnJAVe4n+T4u3RD+dTLDNTqw==
  template:
    metadata:
      name: grafana-ceres-postgres
      namespace: observability
