ingress:
  enabled: false
  className: cilium
  host: argocd.lab.local
  tlsSecretName: argocd-server-tls
  clusterIssuer: letsencrypt
  annotations: {}

cmdParams:
  server:
    insecure: "true"

tlsCertificate:
  enabled: false
  secretName: argocd-server-tls
  commonName: argocd.lab.local
  dnsNames:
    - argocd.lab.local
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: lab-ca-issuer
    kind: ClusterIssuer
