apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: landing-zones
  namespace: argocd
spec:
  description: Business-scoped namespaces and applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'