apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-services
  namespace: argocd
spec:
  description: Shared platform services
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'