{{- if .Values.tlsCertificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.tlsCertificate.secretName | quote }}
  namespace: hermes
  labels:
    app.kubernetes.io/name: hermes
    app.kubernetes.io/part-of: hermes
spec:
  secretName: {{ .Values.tlsCertificate.secretName | quote }}
  commonName: {{ .Values.tlsCertificate.commonName | quote }}
  dnsNames:
    {{- toYaml .Values.tlsCertificate.dnsNames | nindent 4 }}
  duration: {{ .Values.tlsCertificate.duration | quote }}
  renewBefore: {{ .Values.tlsCertificate.renewBefore | quote }}
  issuerRef:
    name: {{ .Values.tlsCertificate.issuerRef.name | quote }}
    kind: {{ .Values.tlsCertificate.issuerRef.kind | quote }}
{{- end }}
