{{- if .Values.cortana.soul }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: hermes-cortana-soul
  namespace: hermes
  labels:
    app.kubernetes.io/name: hermes
    app.kubernetes.io/part-of: hermes
data:
  SOUL.md: |-
    {{- .Values.cortana.soul | nindent 4 }}
{{- end }}
