{{- if and .Values.git.enabled .Values.git.ssh.sealedSecret.encryptedKey }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.git.ssh.secretName | quote }}
  namespace: hermes
  labels:
    app.kubernetes.io/name: hermes
    app.kubernetes.io/part-of: hermes
spec:
  encryptedData:
    {{ .Values.git.ssh.secretKey }}: {{ .Values.git.ssh.sealedSecret.encryptedKey }}
  template:
    metadata:
      name: {{ .Values.git.ssh.secretName | quote }}
      namespace: hermes
    type: Opaque
{{- end }}
