apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-openai-api-key
  namespace: hermes
spec:
  encryptedData:
    api-key: AgAlb/K4qA3IEUGr+QbZ4oWo9eG9rLSofPNMgQohSHSnMsY4qgci5UapZK7Uwvf9MCUzJ5pdXEQH3h5lE9sh8j2dmpWh1QE5JvD/y94vqHPcseRgGiyLdQjm5WOUkHPsjLR4MqgDDOfB4gKgwrJpxxZQkS0wAhaV/W5Dkg3noQdjIZWJ6YzYSuypWrRS5r3NVakw2EOLa0sFrE+S+eq98ckzH9WulU5JSJ0gz3qr6vV5rstfWU8BqiU2lziUdH112wdW9a1XQluMO21cB+YEpTDc4dqHkHo1BMbYiusfB7lCMsrUAGDbWniOf4EQHSGjsJCk4DauzJphFrvq24o4GmUKfcd2rpmp5R52emLu1Y99BP/DWP5/tri7+0aA5V0YoUgVEVf8YR3bwr1wxU7bc4CgM3Wl0DA+7N8cFVtWQMQpCl5dFdc02HXa6DeXV/7S866T1DHG1Kgd9lC0865qnlsajpCooE+p3f9W4HzaJ9Yff1+EBoawfeullI0H1CyB18j6Ldeso35JgG3fX8CDN/VnmE3HFGoyrrKZ8XHkbPucTQDnCGHJjh6U07ZwUyiK8h9Do7a2yzJwZpx+VXtlKUY8KUrImfv2emgbZxPUAj1hsAD60xeFtaa1dizCd/u9tDzfHDPJLajpvccxHYPKqYZ/dt+xWSwKU9tXHDLFWEs0ur1iToD4tADbYNNz6EKvyvgT/CySuVG2GNANgApRNKJroCf57VBsuwHYPQfY5AriZJD5p6nzNtwrGzYCLBAW/sEMlUmfmA+G78BDI5aMRf7FTutfEfZAY5i3oZjHGoknPAjRW36hKwCREVsKz0NszVUhpw9RQAFGcaFQtqcFW+YeqpQWoB/jRlx+/4X0AJMATjj351IN+K9D0Am1Rtff7ruCoKGu56mJU4Qe1/9sD87tCaQxFw==
  template:
    metadata:
      name: hermes-openai-api-key
      namespace: hermes
    type: Opaque
