{{- range $s := list (dict "v" .Values.secrets "type" "Opaque") (dict "v" .Values.coreToken "type" "kubernetes.io/tls") (dict "v" .Values.ciRobot "type" "Opaque") (dict "v" .Values.actionsRobot "type" "Opaque") }}
{{- if $s.v.encryptedData }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $s.v.name }}
  namespace: {{ $.Values.namespace }}
spec:
  encryptedData:
    {{- range $k, $v := $s.v.encryptedData }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ $s.v.name }}
      namespace: {{ $.Values.namespace }}
    type: {{ $s.type }}
{{- end }}
{{- end }}
