apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: platform-services
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 82.2.1
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/config/lab/observability.yaml
    - repoURL: https://github.com/jellebens/gitops.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true