apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: platform-services
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  sources:
    - repoURL: {{ .Values.repos.prometheus.url | quote }}
      chart: kube-prometheus-stack
      targetRevision: {{ .Values.repos.prometheus.targetRevision | quote }}
      helm:
        releaseName: kube-prometheus-stack
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/.config/shared/values.yaml
          - $values/config/shared/values.yaml
          - $values/.config/{{ .Values.environment | default "lab" }}/values.yaml
          - $values/config/{{ .Values.environment | default "lab" }}/values.yaml
          - $values/.config/{{ .Values.environment | default "lab" }}/observability.yaml
          - $values/config/{{ .Values.environment | default "lab" }}/observability.yaml
    - repoURL: {{ .Values.repos.config.url | quote }}
      targetRevision: {{ .Values.repos.config.targetRevision | quote }}
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true