apiVersion: v1
kind: ConfigMap
metadata:
  name: openclaw-config
  namespace: openclaw
  labels:
    app.kubernetes.io/name: openclaw
    app.kubernetes.io/part-of: openclaw
data:
  openclaw.json: |-
    {{- toJson .Values.config | nindent 4 }}
