apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-openai-api-key
  namespace: openclaw
spec:
  encryptedData:
    api-key: AgCDF+ZbGMLE5bnWO86lNu8Gxz1F89IQJh4gF8Wa4ZOjSqzuEG4Zn6ODATxSsNd5HLhNh/7Oqh9t6mvkdqxvbUm0nXSt7XNCBHxssbj2RKWfHL3hID9yl5NY0uFLqNKLto4PBT8ehNCZWBGKwEOX+Kota98rPm7BdIy6oeQhMAyzvWYOYjmUG4dW8zqO6+o8qa7Kjrg6WNrwCm2FB/Nj0vfC7tod/Ek45m0Koc8E7FjGVTZWoC60hV5w3Z74pX8t7AuGcg6IF25As4jMfLa0gY2AXR3zNDEbofFsRwaOBlK/khDn8WPqept9uwRE/vKQPI+cJu+2+1bgv/4iNaoh6aEsLX5vkDsVIEgq7LJPRhRUhmwpFqVdHnyZtPj/UKG9aeJHHhVhrN5FXqD+ybNR8pUa9PjLyDYbnHR7rjmUZOThEgaqrYdR6RcAz+fXo6d9lQ1s12LuWFNOt/+mwITvEQtPFVHjqZPg7js7EM/LLcltR+PqWR9nmiJ1bZS6FgL+yiTbE6C7e+sWRsF0O78H8eiF7uS8gnjCvpZcZTSkZVh4iQrCNdMgMNhxgFXL1wRMwQY4XKi1xPtXuum7W0imcfsojV7SvHi3GpJW0F6FpxtI6Vb93aip8tjdXg1RMYg3vBLGiCQr/pQ/EtaHNAC12JiCtaJDtkkzW1bzkpQoAOP1C17fEDDbCH68hkQnapHnFdk72o39D2GVLlBNRl9MWZbAAaRq0qUNuaMjeCtH1+tyg8s5p5brmjrFJyotKewIA0RvjGZSf5bhJudyMmGRgAKteG82oxGg69X4U7vtu2SCxYX403EuaSGbn2ClUk3pQ3iGyexQBlVXshVpnWIErom/xLkMBOyfOB1hCfNUXoXpABj9nQfjSCN+xJWw1dJh+G4izOs6Vd7LkwLg28cWOcCqllpYmA==
  template:
    metadata:
      name: openclaw-openai-api-key
      namespace: openclaw