apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-gateway-token
  namespace: openclaw
spec:
  encryptedData:
    gateway-token: AgBXfPr8bo7AGgbleh4oNJjawiBp5p2WNNf/ca04+Jzal5t+rpOMQmnGGT13U7zcjlnFIFkIGo3n2VQKS3fNcdimJtMvrLMwgU/VWuFDm+vcACO3m4Ysj4X1KNW2juuvCs37CWn1jVyK+tmzBBl4IcGblmtOa5jCgRq/dd1fk49JkFTlZAbNTCqSVC536feJzYiBm3i312NDEby+Bq4YJNNm9cGcPVMnGnHvOI7xHVUUAstiStumZbUpLiN7aCD9uKT+xlEChILYhP2vk0dPUE9/7pQeU/ATB4l7+IUxvUpQHdtqeLcenqwmmHF50TR+JLcBMioUdjqFjKroiOFOoC1ol83Wr4FSxH/xLIbZwkgLBfu9mhbxJ8gZXyVSNSai9tAlwiZaTAsdJsPj7f8Wnwh+BOFEJR86TM7lZW+QN5LIlSc666puwSj+btL+221dGbWzZ3Em4HdmDfpjBiHLOg9ENlaTNqrLZGVOHQbVBuIXMOK40kzRZNwx/2wA6MOUQ0prsln5slif03Ad1DDyCW3bVG5k2SUyIOnBtUbeixt3ONHDutDdb9bflf/1Wnd3etiqRxbIe62FXC2x1dsAC8CiM+b2LAqobtWGF375vSgKs0hscpgZcdKMyBUT+uWLBv+NFk7tGozdBSh8T4ITWYDmsQ0zFGeEPO6i61OS+YDVghhMJjrjmytlnXw/MSfcIr/TxetebynBNXAuOSwpd38JWI+TJhcRjBEBtVUCbRuCjFDDTwCDD28/
  template:
    metadata:
      name: openclaw-gateway-token
      namespace: openclaw
