{{- if .Values.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name | quote }}
spec:
  {{- if eq (default "acme" .Values.clusterIssuer.type) "selfSigned" }}
  selfSigned: {}
  {{- else }}
  acme:
    email: {{ .Values.clusterIssuer.email | quote }}
    server: {{ .Values.clusterIssuer.server | quote }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.privateKeySecretName | quote }}
    solvers:
      - http01:
          ingress:
            ingressClassName: {{ .Values.clusterIssuer.solver.ingressClassName | quote }}
  {{- end }}
{{- end }}
