apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: platform-services
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  sources:
    - repoURL: {{ .Values.repos.certManager.url | quote }}
      chart: cert-manager
      targetRevision: {{ .Values.repos.certManager.targetRevision | quote }}
      helm:
        releaseName: cert-manager
        ignoreMissingValueFiles: true
        values: |
          installCRDs: true
    - repoURL: {{ .Values.repos.config.url | quote }}
      targetRevision: {{ .Values.repos.config.targetRevision | default "HEAD" }}
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
