apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: platform-services
  sources:
    - repoURL: https://github.com/jellebens/gitops.git
      targetRevision: main
      path: platform/gateway-config
      helm:
        releaseName: gateway-config
        valueFiles:
          - $values/.config/shared/values.yaml
          - $values/.config/{{ .Values.environment | default "lab" }}/values.yaml
          - $values/.config/{{ .Values.environment | default "lab" }}/gateway.yaml
    - repoURL: https://github.com/jellebens/gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
